services:
  # Backend API Service
  - type: web
    name: cosmo-stats-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install ts-node && node build-render.js
    startCommand: cd backend && NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
      - key: DB_CONNECTION_STRING
        value: postgresql://cosmo_rlt_user:BpG7RWIjipwdYQMKjXYRua4TcpYffwPL@dpg-d054t79r0fns73d2loeg-a/cosmo_rlt
      - key: CORS_ORIGINS
        value: https://cosmo-stats-frontend.onrender.com,https://cosmo-stats-backend.onrender.com

  # Frontend Static Site
  - type: static
    name: cosmo-stats-frontend
    env: static
    buildCommand: cd frontend && npm install && NODE_ENV=production npm run build
    staticPublishPath: ./frontend/build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 