services:
  - type: web
    name: cosmo-stats-backend
    env: node
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4001
    buildFilter:
      paths:
      - backend/**

  - type: web
    name: cosmo-stats-frontend
    env: node
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm install --save-dev @types/react-router-dom && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://cosmo-stats-backend.onrender.com
      - key: PORT
        value: 4000
    buildFilter:
      paths:
      - frontend/** 